trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - master

jobs:
- job: Windows
  pool:
    vmIMage: 'VS2017-Win2016'
  variables:
    MNE_LOGGING_LEVEL: 'warning'
    MNE_FORCE_SERIAL: 'true'
    PIP_DEPENDENCIES: 'codecov'
    OPENBLAS_NUM_THREADS: 1
    AZURE_CI_WINDOWS: 'true'
  strategy:
    maxParallel: 4
    matrix:
      # Eventually we should test x86 (32-bit), but it was a nightmare
      # to get it to download 32-bit Anaconda properly, and VTK does not ship
      # 32-bit Windows binaries via pip.
      Python37-64bit-full-pip:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: 'x64'
        TEST_MODE: 'pip'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      architecture: $(PYTHON_ARCH)
      addToPath: true
    condition: eq(variables['TEST_MODE'], 'pip')
  - powershell: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      $PSDefaultParameterValues['*:ErrorAction']='Stop'
      pip install --upgrade numpy scipy vtk
      pip install --upgrade -r requirements.txt
      pip install $env:PIP_DEPENDENCIES
    condition: eq(variables['TEST_MODE'], 'pip')
    displayName: 'Install dependencies with pip'
  - script: python setup.py develop
    displayName: 'Install vtki dev'
  - script: python -c "import vtki; print(vtki.__version__)"
    displayName: 'Print config'
  - script: pytest -v
    displayName: 'Run tests'
  - script: codecov --root %BUILD_REPOSITORY_LOCALPATH% -t %CODECOV_TOKEN%
    displayName: 'Codecov'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
    condition: always()
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
    condition: always()
